config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users
  root to: 'pages#home'
  get 'pages/thankyou'
  resources :profiles
  resources :parkings do
      member do
        get 'state', to: 'parkings#state'
    end
    resources :bookings
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :parking
  belongs_to :profile

  after_create :send_new_booking_email

  private

  def send_new_booking_email
    BookingMailer.creation_confirmation(self).deliver_now
  end

end

app/models/parking.rb
class Parking < ApplicationRecord
  has_many :bookings
  belongs_to :profile
end

app/models/profile.rb
class Profile < ApplicationRecord
belongs_to :user
has_many :bookings, dependent: :destroy
has_many :parkings
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  after_create :send_welcome_email

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :profile

  private

  def send_welcome_email
    UserMailer.welcome(self).deliver_now
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
  end

  def show
  end

  def new
    @booking = Booking.new
  end

  def create

    if current_user.nil?
      flash[:alert] = 'Please signup before booking.'
      return redirect_to new_user_session_path
    end

    @profile = current_user.profile

    if @profile.nil?
      flash[:alert] = 'Please complete your profile before booking.'
      return redirect_to new_profile_path(@profile)
    end

    @parking = Parking.find(params[:parking_id])
    # @booking = Booking.new(booking_params)
    @booking = Booking.new
    @booking.parking = @parking
    @booking.profile = @profile
    # authorize @booking

    if @booking.save
      # flash[:notice] = 'Booking was successfully created.'
      BookingMailer.creation_confirmation(@booking).deliver_now
      # BookingAdminMailer.admin_creation_confirmation(@booking).deliver_now
       @parking.status = "Not Available"
       @parking.stamp = DateTime.now.strftime('%s').to_i
       @parking.save
       redirect_to pages_thankyou_path
    else
      flash[:alert] = 'Booking has been not created'
      # BookingMailer.no_creation_confirmation(@booking).deliver_now
      # BookingAdminMailer.admin_no_creation_confirmation(@booking).deliver_now
      redirect_to parking_path(@parking)
    end

  end

  def edit
  end

  def update
  end

  def destroy
  end

  # private

  # def booking_params
  #   params.require(:booking).permit(:start_date, :end_date, :status)
  # end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/parkings_controller.rb
class ParkingsController < ApplicationController

  def index
  @parkings = Parking.where(status: "Available").sort_by{ |p| [p.stamp] }.reverse!
  @parking = @parkings.last
  end

  def show
    parking = Parking.find(params[:id])
    @MyBookings = Booking.all.where(parking_id: parking.id)
    @profile = current_user.profile
  end

  def state
    @parking = Parking.find(params[:id])
    @profile = current_user.profile
    if @parking.status == "Available"
      @parking.status = "Not Available"
      @parking.stamp = DateTime.now.strftime('%s').to_i
      @parking.save
      flash[:alert] = 'Parking Not Available.'
    elsif
      @parking.status == "Not Available"
      @parking.status = "Available"
      @parking.stamp = DateTime.now.strftime('%s').to_i
      @parking.save
      flash[:notice] = 'Parking Available.'
    end
      redirect_to profile_path(@profile)



  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def index
    @profiles = Profile.all
  end

  def show
    @profile = current_user.profile
    @parkings = Parking.all
  end

  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.new(profile_params)
    @profile.user = current_user
    if @profile.save
      flash[:notice] = 'Profile was successfully created.'
      redirect_to profile_path(@profile)
    else
      flash[:notice] = 'Your profile has not been created, please update your profile later.'
      redirect_to root_path
    end
  end

  def edit
    @profile = current_user.profile
  end

  def update
    @profile = current_user.profile
    if @profile.update(profile_params)
      flash[:notice] = 'Profile was successfully updated.'
      redirect_to profile_path(@profile)
    else
      flash[:notice] = 'Error.  Something went wrong.'
      render :edit
    end
  end

  private

  def profile_params
  params.require(:profile).permit(:first_name, :last_name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

def randomized_background_image
  images = ['assets/bmw.jpeg', 'assets/audi.jpg', 'assets/mercedes.jpg']
  images.sample
end

end

app/views/bookings/index.html.erb
<h2> Index </h2>

app/views/bookings/show.html.erb
<h2> Show </h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
            <!-- Required meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="author" content="Surjith S M">
    <meta name="description" content="#">
    <meta name="keywords" content="#">
    <title>Parking Management</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->

    <!-- Favicons -->
    <link rel="shortcut icon" href="#">
    <!-- Page Title -->
    <title>Listed</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="/assets/vendor/bootstrap.min.css">
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900" rel="stylesheet">
    <!-- Themify Icon -->
    <link rel="stylesheet" href="/assets/vendor/themify-icons.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="/assets/vendor/font-awesome.min.css">
    <!-- line icons -->
    <link rel="stylesheet" href="/assets/vendor/simple-line-icons.css">
    <!-- Swipper Slider -->
    <link rel="stylesheet" href="/assets/vendor/swiper.min.css">
    <!-- Magnific Popup CSS -->
    <link rel="stylesheet" href="/assets/vendor/magnific-popup.css">
    <!-- Hover Effects -->
    <!-- <link href="css/set1.css" rel="stylesheet"> -->
    <!-- Main CSS -->
    <link rel="stylesheet" href="/assets/vendor/_style.scss">

    <%= favicon_link_tag '/assets/logo.png' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
        <!-- jQuery, Bootstrap JS. -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
<!--     <script src="/assets/jquery-3.2.1.min.js"></script>
    <script src="/assets/popper.min.js"></script>
    <script src="/assets/bootstrap.min.js"></script> -->

    <!-- Magnific popup JS -->
    <script src="/assets/jquery.magnific-popup.js"></script>
    <!-- Swipper Slider JS -->
    <script src="/assets/swiper.min.js"></script>
    <script>
        var swiper = new Swiper('.swiper-container', {
            slidesPerView: 3,
            slidesPerGroup: 3,
            loop: true,
            loopFillGroupWithBlank: true,
            pagination: {
                el: '.swiper-pagination',
                clickable: true,
            },
            navigation: {
                nextEl: '.swiper-button-next',
                prevEl: '.swiper-button-prev',
            },
        });
    </script>
    <script>
        if ($('.image-link').length) {
            $('.image-link').magnificPopup({
                type: 'image',
                gallery: {
                    enabled: true
                }
            });
        }
        if ($('.image-link2').length) {
            $('.image-link2').magnificPopup({
                type: 'image',
                gallery: {
                    enabled: true
                }
            });
        }
    </script>
  </body>
</html>

app/views/pages/home.html.erb
<%= render 'shared/banner' %>

app/views/pages/thankyou.html.erb
    <!--============================= CONFIRMATION =============================-->
    <section class="main-block">
        <div class="container-fluid">
            <div class="row justify-content-center align-items-center  min-height-block">
                <div class="col-md-12">
                    <div class="confirmation-wrap">
                        <span class="ti-check"></span>
                        <h2>Thank you for your booking</h2>
                        <p>You'll receive a confirmation email at <%= current_user.email %></p>
                        <% @profile = Profile.where(user_id: current_user.id).first.id  %>
                        <p><%= link_to 'BACK TO MY PROFILE', profile_path(@profile), class: 'btn btn-outline-danger btn-confirmation'%></p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--//END CONFIRMATION -->

app/views/parkings/edit.html.erb
<h2> Edit </h2>

app/views/parkings/new.html.erb
<h2> New </h2>

app/views/profiles/edit.html.erb
<h2> Edit </h2>
<%= render "form", profile: @profile %>

app/views/profiles/new.html.erb
<%= render "form", profile: @profile %>

app/views/profiles/show.html.erb
<% @bookings = Booking.where(profile_id: @profile.id) %>
<% @bookings.each do |booking| %>
<% booking.parking_id %>
<% booking.created_at %>
<% owner_id = Parking.where(id: booking.parking_id)[0].profile_id %>
<% end %>


    <!--============================= BOOKING DETAILS =============================-->
    <% @bookings = Booking.where(profile_id: @profile.id) %>
    <% @my_bookings = Booking.where(profile_id: @profile.id) %>
    <% if @my_bookings != [] && @my_bookings.last.created_at.strftime("%m/%d/%Y") == Time.now.strftime("%m/%d/%Y")  %>
    <% @current_booking = true  %>
    <% end  %>
    <section class="gray-dark booking-details_wrap">
        <div class="container">
            <div class="row">
                <div class="col-md-8 responsive-wrap">
                    <div class="booking-checkbox_wrap my-4">
                        <h4>Current Booking</h4>
                        <hr>
                        <% if @current_booking == true %>
                          <div class="customer-review_wrap">
                              <div class="customer-content-wrap" style="margin-left: 0px">
                                  <div class="customer-content">
                                      <div class="customer-review">
                                          <h6>Parking #<%= Parking.where(id: @my_bookings.last.parking_id)[0].number %></h6>
                                          <p style="margin-left: 0px; font-size: 14px;">Booked on <%= @my_bookings.last.created_at.strftime("%m/%d/%Y") %></p><br>
                                          <p style="margin-left: 0px; font-size: 14px">will be avaialble tomorrow <%= Date.tomorrow.strftime('%m/%d/%Y') %></p>
                                      </div>
                                  </div>
                              </div>
                          </div>
                        <% else  %>
                          <div class="customer-review_wrap">
                                <div class="customer-content-wrap" style="margin-left: 0px">
                                    <div class="customer-content">
                                        <div class="customer-review">
                                            <h6>No parking booked for tomorrow</h6>
                                        </div>
                                        <%= link_to "Book Now", parkings_path, style:"    background: #46cd38; padding: 4px 16px; float: right; color: #fff; border-radius: 3px; border: none; font-size: 16px" %>
                                    </div>
                                </div>
                            </div>
                        <% end  %>
                        <hr>
                    </div>


                    <div class="booking-checkbox_wrap my-4">
                        <h4>Past Bookings</h4>
                        <hr>
                        <% if @bookings != [] %>
                          <% @bookings.each do |booking| %>
                            <% if booking.created_at.strftime("%m/%d/%Y") != Time.now.strftime("%m/%d/%Y") %>
                                  <div class="customer-review_wrap">
                                      <div class="customer-content-wrap" style="margin-left: 0px">
                                          <div class="customer-content">
                                              <div class="customer-review">
                                                  <h6>Parking #<%= Parking.where(id: booking.parking_id)[0].number %></h6>
                                                  <% a = booking.created_at + 1440.minutes %>
                                                  <p style="margin-left: 0px; font-size: 14px">Booked on <%= booking.created_at.strftime("%m/%d/%Y")  %></p><br>
                                                  <p style="margin-left: 0px; font-size: 14px">Was avaialble on <%= a.strftime("%m/%d/%Y") %></p>
                                              </div>
                                          </div>
                                      </div>
                                  </div>
                                  <hr>
                            <% end  %>
                          <% end %>
                        <% else %>
                          <div class="customer-review_wrap">
                                      <div class="customer-content-wrap" style="margin-left: 0px">
                                          <div class="customer-content">
                                              <div class="customer-review">
                                                  <h6>No parking booked yet 😥</h6>
                                              </div>
                                          </div>
                                      </div>
                                  </div>
                                  <hr>
                        <% end %>
                    </div>

<% owner_id = @profile.id %>
<% @MyParkings = Parking.where(profile_id: owner_id) %>


                  <% if @MyParkings.empty? == false %>
                    <div class="booking-checkbox_wrap my-4">
                        <h4>My Parking</h4>
                        <hr>
                          <% @MyParkings.each do |parking| %>
                            <div class="customer-review_wrap">
                                <div class="customer-content-wrap" style="margin-left: 0px">
                                    <div class="customer-content">
                                            <div class="customer-review">
                                                <%= link_to "Parking ##{parking.number}", parking_path(parking.id), style:"color: #73cf42 !important; font-size: 16px; border: none; padding-left: 0px; font-weight: 500; line-height: 1.1; font-family: inherit;" %>
                                                <h6> </h6>
                                                <p style="margin-left: 0px; font-size: 14px">Parking status: <%= parking.status %></p>
                                            </div>
                                            <!-- can't change status if parking currently booked -->
                                            <% @MylastBooking = Booking.all.where(parking_id: parking.id).last  %>
                                            <% if @MylastBooking.nil? == false  %>
                                                <% booking = @MylastBooking  %>
                                                <% @BookingDate = booking.created_at.strftime("%m/%d/%Y")  %>

                                                <% if @BookingDate == Time.now.strftime("%m/%d/%Y")  %>
                                                  <p style="float: right; font-size: 16px;  padding-top: 12.5px; padding-bottom: 12.5px; color: #ff6b6b !important; border: none">Rent /status can't be amended✋</p>
                                                <% else %>
                                                  <% if parking.status == "Available" %>
                                                    <%= link_to "Make it unavailable", state_parking_path(parking.id), style:"    background: #ff6b6b; padding: 4px 16px; float: right; color: #fff; border-radius: 3px; border: none; font-size: 16px" %>
                                                  <% else  %>
                                                    <%= link_to "Make it available", state_parking_path(parking.id), style:"    background: #46cd38; padding: 4px 16px; float: right; color: #fff; border-radius: 3px; border: none; font-size: 16px" %>
                                                  <% end  %>
                                                <% end  %>
                                            <% else  %>
                                              <% if parking.status == "Available" %>
                                                    <%= link_to "Make it unavailable", state_parking_path(parking.id), style:"    background: #ff6b6b; padding: 4px 16px; float: right; color: #fff; border-radius: 3px; border: none; font-size: 16px" %>
                                              <% else  %>
                                                    <%= link_to "Make it available", state_parking_path(parking.id), style:"    background: #46cd38; padding: 4px 16px; float: right; color: #fff; border-radius: 3px; border: none; font-size: 16px" %>
                                              <% end  %>
                                            <% end  %>
                                    </div>
                                </div>
                            </div>
                            <hr>
                          <% end %>
                    </div>
                  <% end  %>




                </div>

                <div class="col-md-4 responsive-wrap">
                    <div class="follow" style="padding-bottom: 15px;">
                        <div class="follow-img">
                            <img src="/assets/follow-img.jpg" class="img-fluid" alt="#">
                            <h6><%= @profile.first_name %> <%= @profile.last_name %>, id #<%= @profile.id %></h6>
                            <span>Luxembourg</span>
                        </div>
                        <ul class="d-flex">
                              <li class=" flex-fill">
                                  <h6> <%= @my_bookings.count %> </h6>
                                  <span>bookings</span>
                              </li>
                          <% if @bookings.empty? == false %>
                              <li class=" flex-fill">
                                  <% last_booking =  @bookings.all.sort_by {|booking| booking.created_at}.last %>
                                  <h6><%= last_booking.created_at.strftime("%m/%d/%Y") %></h6>
                                  <span>last booking</span>
                              </li>
                          <% else  %>
                              <li class=" flex-fill">
                                  <h6> - </h6>
                                  <span>last booking</span>
                              </li>
                          <% end  %>
                        </ul>
                        <p><%= link_to 'EDIT MY PROFILE', edit_profile_path(@profile), class: 'btn btn-outline-danger btn-contact'%></p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--//END BOOKING DETAILS -->

app/views/shared/_banner.html.erb
<% if user_signed_in? %>
  <% if current_user && current_user.profile %>

      <% @profile = current_user.profile  %>
      <% @bookings = Booking.where(profile_id: @profile.id) %>
      <% @my_bookings = Booking.where(profile_id: @profile.id) %>
      <% if @my_bookings != [] && @my_bookings.last.created_at.strftime("%m/%d/%Y") == Time.now.strftime("%m/%d/%Y")  %>
      <% @current_booking = true  %>
      <% end  %>
  <% end  %>
<% end  %>


<section class="hero-wrap d-flex align-items-center " style="background-color: white; height: calc(100vh);">
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="hero-title">
                <h1>Where will you park tomorrow?</h1>
                <h3>Find out the perfect parking lot to park your car where you work</h3>
            </div>
        </div>
        <div class="row d-flex justify-content-center">
            <div class="hero-title">
                      <% if @current_booking == true %>
                        <%= link_to "Can't book twice 😞", root_path, disabled: true, class: 'btn btn-simple', style:"color: white; padding: 20px 46px; font-size: 18px;background: #ff6b6b; border-radius: 6px; margin: 100px 0px"  %>
                      <% else  %>
                        <%= link_to 'Search →', parkings_path, class: 'btn btn-simple', style:"color: white; padding: 20px 46px; font-size: 18px;background: #ff6b6b; border-radius: 6px; margin: 100px 0px" %>
                      <% end  %>
            </div>



        </div>


<!--         <div class="row d-flex justify-content-center">
            <div class="hero-title demo" id="section10">


                 <a style="color: #7c7c7c;font-family: 'Roboto', sans-serif; font-size: 14px"><span></span>scroll down</a>

            </div>



        </div> -->















        <!-- <div class="row">
            <div class="col-md-12">
                <form>
                    <div class="search-box">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="search-box2">
                                    <div class="search-box-title" style="padding-top: 0px">
                                        <label>Book your parking for tomorrow <%= Date.tomorrow.strftime('%m/%d/%Y')  %></label><br>
                                        <p style="font-weight: 300; font-size: 18px; color: #484848;    margin-bottom: 0px;">As a reminder, the car park you are looking for is within BIL</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="btn-search">
                      <% if @current_booking == true %>
                        <%= link_to "Can't book twice 😞", root_path, disabled: true, class: 'btn btn-simple', style:"opacity: 1;"  %>
                      <% else  %>
                        <%= link_to 'Search →', parkings_path, class: 'btn btn-simple' %>
                      <% end  %>
                    </div>
                </form>
                <p class="search-bottom-title">By using this website, you are agreeing to our  <span style="text-decoration: underline;">terms and conditions</span></p>
            </div>
        </div> -->
    </div>
</section>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<!--============================= HEADER =============================-->
    <div class="nav-menu sticky-top">
        <div class="bg transition">
            <div class="container-fluid fixed">
                <div class="row">
                    <div class="col-md-12">
                        <nav class="navbar navbar-expand-lg">
                            <%= link_to root_path, class: "navbar-wagon-brand" do %><%= image_tag "logo.png" %><% end %>
                            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="ti-menu"></span>
                            </button>
                            <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
                                  <% if user_signed_in? %>
                                    <% if current_user && current_user.profile && current_user.admin %>
                                                            <ul class="navbar-nav">
                                                                  <li class="nav-item"><%= link_to "Admin", admin_root_path, class: "nav-link", target:"_blank" %></li>
                                                                  <li class="nav-item"><%= link_to "Profile", profile_path(current_user.profile), class: "nav-link" %></li>
                                                                  <li class="nav-item"><%= link_to destroy_user_session_path, class: "nav-link", method: :delete do %><%= t(".sign_out", default: "Log out") %><% end %></li>
                                                            </ul>
                                    <% elsif current_user && current_user.profile %>
                                                            <ul class="navbar-nav">
<!-- management parking status within navbar -->
<% @profile = current_user.profile  %>
<% owner_id = @profile.id %>
<% @MyParkings = Parking.where(profile_id: owner_id) %>

<li>
<% if @MyParkings.empty? == false %>
          <% @MyParkings.each do |parking| %>
                            <!-- can't change status if parking currently booked -->
                                            <% @MylastBooking = Booking.all.where(parking_id: parking.id).last  %>
                                            <% if @MylastBooking.nil? == false  %>
                                                <% booking = @MylastBooking  %>
                                                <% @BookingDate = booking.created_at.strftime("%m/%d/%Y")  %>

                                                <% if @BookingDate == Time.now.strftime("%m/%d/%Y")  %>
                                                  <p style="float: right; font-size: 16px;  padding-top: 12.5px; padding-bottom: 12.5px; line-height: 25px;color: #ff6b6b !important; border: none">Currently rent, status can't be amended ✋</p>
                                                <% else %>
                                                  <% if parking.status == "Available" %>
                                                    <%= link_to "Make it unavailable", state_parking_path(parking.id), style:"    background: #ff6b6b; padding: 12px; float: right; color: #fff; border-radius: 3px; border: none; font-size: 16px; text-decoration: none" %>
                                                  <% else  %>
                                                    <%= link_to "Make it available", state_parking_path(parking.id), style:"    background: #46cd38; padding: 12px; float: right; color: #fff; border-radius: 3px; border: none; font-size: 16px; text-decoration: none" %>
                                                  <% end  %>
                                                <% end  %>
                                            <% else  %>
                                              <% if parking.status == "Available" %>
                                                    <%= link_to "Make it unavailable", state_parking_path(parking.id), style:"    background: #ff6b6b; padding: 12px; float: right; color: #fff; border-radius: 3px; border: none; font-size: 16px; text-decoration: none" %>
                                              <% else  %>
                                                    <%= link_to "Make it available", state_parking_path(parking.id), style:"    background: #46cd38; padding: 12px; float: right; color: #fff; border-radius: 3px; border: none; font-size: 16px; text-decoration: none" %>
                                              <% end  %>
                                            <% end  %>
          <% end %>
  <% end  %>
</li>
<!-- end: management parking status within navbar -->
                                                                  <li class="nav-item"><%= link_to "Profile", profile_path(current_user.profile), class: "nav-link" %></li>
                                                                  <li class="nav-item"><%= link_to destroy_user_session_path, class: "nav-link", method: :delete do %><%= t(".sign_out", default: "Log out") %><% end %></li>



                                                            </ul>
                                    <% else %>
                                                            <ul class="navbar-nav">
                                                                  <li class="nav-item active"><%= link_to "Profile", new_profile_path, class: "nav-link" %></li>
                                                                  <li class="nav-item"><%= link_to destroy_user_session_path, class: "nav-link", method: :delete do %><%= t(".sign_out", default: "Log out") %><% end %></li>
                                                            </ul>
                                    <% end %>
                                  <% else %>
                                                            <ul class="navbar-nav"><li class="nav-item"><%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "nav-link" %></li>
                                                            </ul>
                                  <% end %>
                            </div>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!--//END HEADER -->